apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rollback-demo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    # CHANGE THIS to your new repo URL:
    repoURL: https://github.com/yshwntsingh/argocd-rollback-demo.git
    targetRevision: main
    path: k8s/
  destination:
    server: https://kubernetes.default.svc
    namespace: demoapp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true      # this is why rollback MUST be done in Git, not kubectl
    syncOptions:
      - CreateNamespace=true
